### ISSUE TITLE
convert to gregorian

### ISSUE THREAD

**Issue by moeinserpico** [babakhani/PersianDate#63]
how to convert persian date that is created via pdatepicker  to geregorian

**Comment by hosseincode** [comment]
I think what you want to do is to display the persian date on the input but also have it converted to gregorian to store in database? if thats the case you can use the onSelect method of the pdatepicker which returns the unix date. You can convert that to gregorian.

```
$(document).ready(function() {
    $("#date").pDatepicker({
        "onSelect": function(time) {
            gregorianDate = new persianDate(time).toDate();
        }
    })
})
```
Instead of using toDate() on it you can use something like this too:

`gregorianDate = new persianDate(time).toCalendar('gregorian').toLocale('en').format('MMMM')`

Change the 'MMMM' to better suit your needs.

Not sure if this is the best way to do it or there's a better solution but it'll get you going.

**Comment by moeinserpico** [comment]
Thanks 
but if user leave control for default val
how can I read gregorian value from it?
